/*
Mistral AI API

Testing BetaLibrariesDocumentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mistral

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/wbhob/mistral"
)

func Test_mistral_BetaLibrariesDocumentsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BetaLibrariesDocumentsAPIService LibrariesDocumentsDeleteV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var libraryId string
		var documentId string

		httpRes, err := apiClient.BetaLibrariesDocumentsAPI.LibrariesDocumentsDeleteV1(context.Background(), libraryId, documentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaLibrariesDocumentsAPIService LibrariesDocumentsGetExtractedTextSignedUrlV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var libraryId string
		var documentId string

		resp, httpRes, err := apiClient.BetaLibrariesDocumentsAPI.LibrariesDocumentsGetExtractedTextSignedUrlV1(context.Background(), libraryId, documentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaLibrariesDocumentsAPIService LibrariesDocumentsGetSignedUrlV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var libraryId string
		var documentId string

		resp, httpRes, err := apiClient.BetaLibrariesDocumentsAPI.LibrariesDocumentsGetSignedUrlV1(context.Background(), libraryId, documentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaLibrariesDocumentsAPIService LibrariesDocumentsGetStatusV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var libraryId string
		var documentId string

		resp, httpRes, err := apiClient.BetaLibrariesDocumentsAPI.LibrariesDocumentsGetStatusV1(context.Background(), libraryId, documentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaLibrariesDocumentsAPIService LibrariesDocumentsGetTextContentV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var libraryId string
		var documentId string

		resp, httpRes, err := apiClient.BetaLibrariesDocumentsAPI.LibrariesDocumentsGetTextContentV1(context.Background(), libraryId, documentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaLibrariesDocumentsAPIService LibrariesDocumentsGetV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var libraryId string
		var documentId string

		resp, httpRes, err := apiClient.BetaLibrariesDocumentsAPI.LibrariesDocumentsGetV1(context.Background(), libraryId, documentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaLibrariesDocumentsAPIService LibrariesDocumentsListV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var libraryId string

		resp, httpRes, err := apiClient.BetaLibrariesDocumentsAPI.LibrariesDocumentsListV1(context.Background(), libraryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaLibrariesDocumentsAPIService LibrariesDocumentsReprocessV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var libraryId string
		var documentId string

		httpRes, err := apiClient.BetaLibrariesDocumentsAPI.LibrariesDocumentsReprocessV1(context.Background(), libraryId, documentId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaLibrariesDocumentsAPIService LibrariesDocumentsUpdateV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var libraryId string
		var documentId string

		resp, httpRes, err := apiClient.BetaLibrariesDocumentsAPI.LibrariesDocumentsUpdateV1(context.Background(), libraryId, documentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BetaLibrariesDocumentsAPIService LibrariesDocumentsUploadV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var libraryId string

		resp, httpRes, err := apiClient.BetaLibrariesDocumentsAPI.LibrariesDocumentsUploadV1(context.Background(), libraryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
