/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 0.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type ClassifiersAPI interface {

	/*
	ChatModerationsV1ChatModerationsPost Chat Moderations

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiChatModerationsV1ChatModerationsPostRequest
	*/
	ChatModerationsV1ChatModerationsPost(ctx context.Context) ApiChatModerationsV1ChatModerationsPostRequest

	// ChatModerationsV1ChatModerationsPostExecute executes the request
	//  @return ClassificationResponse
	ChatModerationsV1ChatModerationsPostExecute(r ApiChatModerationsV1ChatModerationsPostRequest) (*ClassificationResponse, *http.Response, error)

	/*
	ModerationsV1ModerationsPost Moderations

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiModerationsV1ModerationsPostRequest
	*/
	ModerationsV1ModerationsPost(ctx context.Context) ApiModerationsV1ModerationsPostRequest

	// ModerationsV1ModerationsPostExecute executes the request
	//  @return ClassificationResponse
	ModerationsV1ModerationsPostExecute(r ApiModerationsV1ModerationsPostRequest) (*ClassificationResponse, *http.Response, error)
}

// ClassifiersAPIService ClassifiersAPI service
type ClassifiersAPIService service

type ApiChatModerationsV1ChatModerationsPostRequest struct {
	ctx context.Context
	ApiService ClassifiersAPI
	chatModerationRequest *ChatModerationRequest
}

func (r ApiChatModerationsV1ChatModerationsPostRequest) ChatModerationRequest(chatModerationRequest ChatModerationRequest) ApiChatModerationsV1ChatModerationsPostRequest {
	r.chatModerationRequest = &chatModerationRequest
	return r
}

func (r ApiChatModerationsV1ChatModerationsPostRequest) Execute() (*ClassificationResponse, *http.Response, error) {
	return r.ApiService.ChatModerationsV1ChatModerationsPostExecute(r)
}

/*
ChatModerationsV1ChatModerationsPost Chat Moderations

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiChatModerationsV1ChatModerationsPostRequest
*/
func (a *ClassifiersAPIService) ChatModerationsV1ChatModerationsPost(ctx context.Context) ApiChatModerationsV1ChatModerationsPostRequest {
	return ApiChatModerationsV1ChatModerationsPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ClassificationResponse
func (a *ClassifiersAPIService) ChatModerationsV1ChatModerationsPostExecute(r ApiChatModerationsV1ChatModerationsPostRequest) (*ClassificationResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ClassificationResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ClassifiersAPIService.ChatModerationsV1ChatModerationsPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/chat/moderations"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.chatModerationRequest == nil {
		return localVarReturnValue, nil, reportError("chatModerationRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.chatModerationRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiModerationsV1ModerationsPostRequest struct {
	ctx context.Context
	ApiService ClassifiersAPI
	classificationRequest *ClassificationRequest
}

func (r ApiModerationsV1ModerationsPostRequest) ClassificationRequest(classificationRequest ClassificationRequest) ApiModerationsV1ModerationsPostRequest {
	r.classificationRequest = &classificationRequest
	return r
}

func (r ApiModerationsV1ModerationsPostRequest) Execute() (*ClassificationResponse, *http.Response, error) {
	return r.ApiService.ModerationsV1ModerationsPostExecute(r)
}

/*
ModerationsV1ModerationsPost Moderations

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiModerationsV1ModerationsPostRequest
*/
func (a *ClassifiersAPIService) ModerationsV1ModerationsPost(ctx context.Context) ApiModerationsV1ModerationsPostRequest {
	return ApiModerationsV1ModerationsPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ClassificationResponse
func (a *ClassifiersAPIService) ModerationsV1ModerationsPostExecute(r ApiModerationsV1ModerationsPostRequest) (*ClassificationResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ClassificationResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ClassifiersAPIService.ModerationsV1ModerationsPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/moderations"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.classificationRequest == nil {
		return localVarReturnValue, nil, reportError("classificationRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.classificationRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
