/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
)

// checks if the FileChunk type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileChunk{}

// FileChunk struct for FileChunk
type FileChunk struct {
	Type *string `json:"type,omitempty"`
	FileId string `json:"file_id"`
	AdditionalProperties map[string]interface{}
}

type _FileChunk FileChunk

// NewFileChunk instantiates a new FileChunk object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileChunk(fileId string) *FileChunk {
	this := FileChunk{}
	var type_ string = "file"
	this.Type = &type_
	this.FileId = fileId
	return &this
}

// NewFileChunkWithDefaults instantiates a new FileChunk object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileChunkWithDefaults() *FileChunk {
	this := FileChunk{}
	var type_ string = "file"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *FileChunk) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileChunk) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *FileChunk) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *FileChunk) SetType(v string) {
	o.Type = &v
}

// GetFileId returns the FileId field value
func (o *FileChunk) GetFileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value
// and a boolean to check if the value has been set.
func (o *FileChunk) GetFileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileId, true
}

// SetFileId sets field value
func (o *FileChunk) SetFileId(v string) {
	o.FileId = v
}

func (o FileChunk) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileChunk) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["file_id"] = o.FileId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FileChunk) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"file_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFileChunk := _FileChunk{}

	err = json.Unmarshal(data, &varFileChunk)

	if err != nil {
		return err
	}

	*o = FileChunk(varFileChunk)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "file_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFileChunk struct {
	value *FileChunk
	isSet bool
}

func (v NullableFileChunk) Get() *FileChunk {
	return v.value
}

func (v *NullableFileChunk) Set(val *FileChunk) {
	v.value = val
	v.isSet = true
}

func (v NullableFileChunk) IsSet() bool {
	return v.isSet
}

func (v *NullableFileChunk) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileChunk(val *FileChunk) *NullableFileChunk {
	return &NullableFileChunk{value: val, isSet: true}
}

func (v NullableFileChunk) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileChunk) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


