/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the AgentHandoffDoneEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentHandoffDoneEvent{}

// AgentHandoffDoneEvent struct for AgentHandoffDoneEvent
type AgentHandoffDoneEvent struct {
	Type *string `json:"type,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	OutputIndex *int32 `json:"output_index,omitempty"`
	Id string `json:"id"`
	NextAgentId string `json:"next_agent_id"`
	NextAgentName string `json:"next_agent_name"`
	AdditionalProperties map[string]interface{}
}

type _AgentHandoffDoneEvent AgentHandoffDoneEvent

// NewAgentHandoffDoneEvent instantiates a new AgentHandoffDoneEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentHandoffDoneEvent(id string, nextAgentId string, nextAgentName string) *AgentHandoffDoneEvent {
	this := AgentHandoffDoneEvent{}
	var type_ string = "agent.handoff.done"
	this.Type = &type_
	var outputIndex int32 = 0
	this.OutputIndex = &outputIndex
	this.Id = id
	this.NextAgentId = nextAgentId
	this.NextAgentName = nextAgentName
	return &this
}

// NewAgentHandoffDoneEventWithDefaults instantiates a new AgentHandoffDoneEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentHandoffDoneEventWithDefaults() *AgentHandoffDoneEvent {
	this := AgentHandoffDoneEvent{}
	var type_ string = "agent.handoff.done"
	this.Type = &type_
	var outputIndex int32 = 0
	this.OutputIndex = &outputIndex
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AgentHandoffDoneEvent) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentHandoffDoneEvent) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AgentHandoffDoneEvent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AgentHandoffDoneEvent) SetType(v string) {
	o.Type = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AgentHandoffDoneEvent) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentHandoffDoneEvent) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AgentHandoffDoneEvent) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AgentHandoffDoneEvent) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetOutputIndex returns the OutputIndex field value if set, zero value otherwise.
func (o *AgentHandoffDoneEvent) GetOutputIndex() int32 {
	if o == nil || IsNil(o.OutputIndex) {
		var ret int32
		return ret
	}
	return *o.OutputIndex
}

// GetOutputIndexOk returns a tuple with the OutputIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentHandoffDoneEvent) GetOutputIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.OutputIndex) {
		return nil, false
	}
	return o.OutputIndex, true
}

// HasOutputIndex returns a boolean if a field has been set.
func (o *AgentHandoffDoneEvent) HasOutputIndex() bool {
	if o != nil && !IsNil(o.OutputIndex) {
		return true
	}

	return false
}

// SetOutputIndex gets a reference to the given int32 and assigns it to the OutputIndex field.
func (o *AgentHandoffDoneEvent) SetOutputIndex(v int32) {
	o.OutputIndex = &v
}

// GetId returns the Id field value
func (o *AgentHandoffDoneEvent) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AgentHandoffDoneEvent) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AgentHandoffDoneEvent) SetId(v string) {
	o.Id = v
}

// GetNextAgentId returns the NextAgentId field value
func (o *AgentHandoffDoneEvent) GetNextAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextAgentId
}

// GetNextAgentIdOk returns a tuple with the NextAgentId field value
// and a boolean to check if the value has been set.
func (o *AgentHandoffDoneEvent) GetNextAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextAgentId, true
}

// SetNextAgentId sets field value
func (o *AgentHandoffDoneEvent) SetNextAgentId(v string) {
	o.NextAgentId = v
}

// GetNextAgentName returns the NextAgentName field value
func (o *AgentHandoffDoneEvent) GetNextAgentName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextAgentName
}

// GetNextAgentNameOk returns a tuple with the NextAgentName field value
// and a boolean to check if the value has been set.
func (o *AgentHandoffDoneEvent) GetNextAgentNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextAgentName, true
}

// SetNextAgentName sets field value
func (o *AgentHandoffDoneEvent) SetNextAgentName(v string) {
	o.NextAgentName = v
}

func (o AgentHandoffDoneEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentHandoffDoneEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.OutputIndex) {
		toSerialize["output_index"] = o.OutputIndex
	}
	toSerialize["id"] = o.Id
	toSerialize["next_agent_id"] = o.NextAgentId
	toSerialize["next_agent_name"] = o.NextAgentName

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AgentHandoffDoneEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"next_agent_id",
		"next_agent_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentHandoffDoneEvent := _AgentHandoffDoneEvent{}

	err = json.Unmarshal(data, &varAgentHandoffDoneEvent)

	if err != nil {
		return err
	}

	*o = AgentHandoffDoneEvent(varAgentHandoffDoneEvent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "output_index")
		delete(additionalProperties, "id")
		delete(additionalProperties, "next_agent_id")
		delete(additionalProperties, "next_agent_name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAgentHandoffDoneEvent struct {
	value *AgentHandoffDoneEvent
	isSet bool
}

func (v NullableAgentHandoffDoneEvent) Get() *AgentHandoffDoneEvent {
	return v.value
}

func (v *NullableAgentHandoffDoneEvent) Set(val *AgentHandoffDoneEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentHandoffDoneEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentHandoffDoneEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentHandoffDoneEvent(val *AgentHandoffDoneEvent) *NullableAgentHandoffDoneEvent {
	return &NullableAgentHandoffDoneEvent{value: val, isSet: true}
}

func (v NullableAgentHandoffDoneEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentHandoffDoneEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


