/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
)

// checks if the ChatModerationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatModerationRequest{}

// ChatModerationRequest struct for ChatModerationRequest
type ChatModerationRequest struct {
	Input Input `json:"input"`
	Model string `json:"model"`
	AdditionalProperties map[string]interface{}
}

type _ChatModerationRequest ChatModerationRequest

// NewChatModerationRequest instantiates a new ChatModerationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatModerationRequest(input Input, model string) *ChatModerationRequest {
	this := ChatModerationRequest{}
	this.Input = input
	this.Model = model
	return &this
}

// NewChatModerationRequestWithDefaults instantiates a new ChatModerationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatModerationRequestWithDefaults() *ChatModerationRequest {
	this := ChatModerationRequest{}
	return &this
}

// GetInput returns the Input field value
func (o *ChatModerationRequest) GetInput() Input {
	if o == nil {
		var ret Input
		return ret
	}

	return o.Input
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
func (o *ChatModerationRequest) GetInputOk() (*Input, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Input, true
}

// SetInput sets field value
func (o *ChatModerationRequest) SetInput(v Input) {
	o.Input = v
}

// GetModel returns the Model field value
func (o *ChatModerationRequest) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *ChatModerationRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *ChatModerationRequest) SetModel(v string) {
	o.Model = v
}

func (o ChatModerationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatModerationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["input"] = o.Input
	toSerialize["model"] = o.Model

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChatModerationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"input",
		"model",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChatModerationRequest := _ChatModerationRequest{}

	err = json.Unmarshal(data, &varChatModerationRequest)

	if err != nil {
		return err
	}

	*o = ChatModerationRequest(varChatModerationRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "input")
		delete(additionalProperties, "model")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChatModerationRequest struct {
	value *ChatModerationRequest
	isSet bool
}

func (v NullableChatModerationRequest) Get() *ChatModerationRequest {
	return v.value
}

func (v *NullableChatModerationRequest) Set(val *ChatModerationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChatModerationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChatModerationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatModerationRequest(val *ChatModerationRequest) *NullableChatModerationRequest {
	return &NullableChatModerationRequest{value: val, isSet: true}
}

func (v NullableChatModerationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatModerationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


