/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
)

// checks if the AgentCreationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentCreationRequest{}

// AgentCreationRequest struct for AgentCreationRequest
type AgentCreationRequest struct {
	Instructions NullableString `json:"instructions,omitempty"`
	// List of tools which are available to the model during the conversation.
	Tools []AgentToolsInner `json:"tools,omitempty"`
	// Completion arguments that will be used to generate assistant responses. Can be overridden at each message request.
	CompletionArgs *CompletionArgs `json:"completion_args,omitempty"`
	Model string `json:"model"`
	Name string `json:"name"`
	Description NullableString `json:"description,omitempty"`
	Handoffs []string `json:"handoffs,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AgentCreationRequest AgentCreationRequest

// NewAgentCreationRequest instantiates a new AgentCreationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentCreationRequest(model string, name string) *AgentCreationRequest {
	this := AgentCreationRequest{}
	this.Model = model
	this.Name = name
	return &this
}

// NewAgentCreationRequestWithDefaults instantiates a new AgentCreationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentCreationRequestWithDefaults() *AgentCreationRequest {
	this := AgentCreationRequest{}
	return &this
}

// GetInstructions returns the Instructions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentCreationRequest) GetInstructions() string {
	if o == nil || IsNil(o.Instructions.Get()) {
		var ret string
		return ret
	}
	return *o.Instructions.Get()
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentCreationRequest) GetInstructionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Instructions.Get(), o.Instructions.IsSet()
}

// HasInstructions returns a boolean if a field has been set.
func (o *AgentCreationRequest) HasInstructions() bool {
	if o != nil && o.Instructions.IsSet() {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given NullableString and assigns it to the Instructions field.
func (o *AgentCreationRequest) SetInstructions(v string) {
	o.Instructions.Set(&v)
}
// SetInstructionsNil sets the value for Instructions to be an explicit nil
func (o *AgentCreationRequest) SetInstructionsNil() {
	o.Instructions.Set(nil)
}

// UnsetInstructions ensures that no value is present for Instructions, not even an explicit nil
func (o *AgentCreationRequest) UnsetInstructions() {
	o.Instructions.Unset()
}

// GetTools returns the Tools field value if set, zero value otherwise.
func (o *AgentCreationRequest) GetTools() []AgentToolsInner {
	if o == nil || IsNil(o.Tools) {
		var ret []AgentToolsInner
		return ret
	}
	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentCreationRequest) GetToolsOk() ([]AgentToolsInner, bool) {
	if o == nil || IsNil(o.Tools) {
		return nil, false
	}
	return o.Tools, true
}

// HasTools returns a boolean if a field has been set.
func (o *AgentCreationRequest) HasTools() bool {
	if o != nil && !IsNil(o.Tools) {
		return true
	}

	return false
}

// SetTools gets a reference to the given []AgentToolsInner and assigns it to the Tools field.
func (o *AgentCreationRequest) SetTools(v []AgentToolsInner) {
	o.Tools = v
}

// GetCompletionArgs returns the CompletionArgs field value if set, zero value otherwise.
func (o *AgentCreationRequest) GetCompletionArgs() CompletionArgs {
	if o == nil || IsNil(o.CompletionArgs) {
		var ret CompletionArgs
		return ret
	}
	return *o.CompletionArgs
}

// GetCompletionArgsOk returns a tuple with the CompletionArgs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentCreationRequest) GetCompletionArgsOk() (*CompletionArgs, bool) {
	if o == nil || IsNil(o.CompletionArgs) {
		return nil, false
	}
	return o.CompletionArgs, true
}

// HasCompletionArgs returns a boolean if a field has been set.
func (o *AgentCreationRequest) HasCompletionArgs() bool {
	if o != nil && !IsNil(o.CompletionArgs) {
		return true
	}

	return false
}

// SetCompletionArgs gets a reference to the given CompletionArgs and assigns it to the CompletionArgs field.
func (o *AgentCreationRequest) SetCompletionArgs(v CompletionArgs) {
	o.CompletionArgs = &v
}

// GetModel returns the Model field value
func (o *AgentCreationRequest) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *AgentCreationRequest) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *AgentCreationRequest) SetModel(v string) {
	o.Model = v
}

// GetName returns the Name field value
func (o *AgentCreationRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AgentCreationRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AgentCreationRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentCreationRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentCreationRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *AgentCreationRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *AgentCreationRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *AgentCreationRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *AgentCreationRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetHandoffs returns the Handoffs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentCreationRequest) GetHandoffs() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Handoffs
}

// GetHandoffsOk returns a tuple with the Handoffs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentCreationRequest) GetHandoffsOk() ([]string, bool) {
	if o == nil || IsNil(o.Handoffs) {
		return nil, false
	}
	return o.Handoffs, true
}

// HasHandoffs returns a boolean if a field has been set.
func (o *AgentCreationRequest) HasHandoffs() bool {
	if o != nil && !IsNil(o.Handoffs) {
		return true
	}

	return false
}

// SetHandoffs gets a reference to the given []string and assigns it to the Handoffs field.
func (o *AgentCreationRequest) SetHandoffs(v []string) {
	o.Handoffs = v
}

func (o AgentCreationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentCreationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Instructions.IsSet() {
		toSerialize["instructions"] = o.Instructions.Get()
	}
	if !IsNil(o.Tools) {
		toSerialize["tools"] = o.Tools
	}
	if !IsNil(o.CompletionArgs) {
		toSerialize["completion_args"] = o.CompletionArgs
	}
	toSerialize["model"] = o.Model
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Handoffs != nil {
		toSerialize["handoffs"] = o.Handoffs
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AgentCreationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"model",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentCreationRequest := _AgentCreationRequest{}

	err = json.Unmarshal(data, &varAgentCreationRequest)

	if err != nil {
		return err
	}

	*o = AgentCreationRequest(varAgentCreationRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "instructions")
		delete(additionalProperties, "tools")
		delete(additionalProperties, "completion_args")
		delete(additionalProperties, "model")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "handoffs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAgentCreationRequest struct {
	value *AgentCreationRequest
	isSet bool
}

func (v NullableAgentCreationRequest) Get() *AgentCreationRequest {
	return v.value
}

func (v *NullableAgentCreationRequest) Set(val *AgentCreationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentCreationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentCreationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentCreationRequest(val *AgentCreationRequest) *NullableAgentCreationRequest {
	return &NullableAgentCreationRequest{value: val, isSet: true}
}

func (v NullableAgentCreationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentCreationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


