/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 0.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchJobsOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchJobsOut{}

// BatchJobsOut struct for BatchJobsOut
type BatchJobsOut struct {
	Data []BatchJobOut `json:"data,omitempty"`
	Object *string `json:"object,omitempty"`
	Total int32 `json:"total"`
}

type _BatchJobsOut BatchJobsOut

// NewBatchJobsOut instantiates a new BatchJobsOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchJobsOut(total int32) *BatchJobsOut {
	this := BatchJobsOut{}
	var object string = "list"
	this.Object = &object
	this.Total = total
	return &this
}

// NewBatchJobsOutWithDefaults instantiates a new BatchJobsOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchJobsOutWithDefaults() *BatchJobsOut {
	this := BatchJobsOut{}
	var object string = "list"
	this.Object = &object
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *BatchJobsOut) GetData() []BatchJobOut {
	if o == nil || IsNil(o.Data) {
		var ret []BatchJobOut
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobsOut) GetDataOk() ([]BatchJobOut, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *BatchJobsOut) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []BatchJobOut and assigns it to the Data field.
func (o *BatchJobsOut) SetData(v []BatchJobOut) {
	o.Data = v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *BatchJobsOut) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchJobsOut) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *BatchJobsOut) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *BatchJobsOut) SetObject(v string) {
	o.Object = &v
}

// GetTotal returns the Total field value
func (o *BatchJobsOut) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *BatchJobsOut) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *BatchJobsOut) SetTotal(v int32) {
	o.Total = v
}

func (o BatchJobsOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchJobsOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *BatchJobsOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchJobsOut := _BatchJobsOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchJobsOut)

	if err != nil {
		return err
	}

	*o = BatchJobsOut(varBatchJobsOut)

	return err
}

type NullableBatchJobsOut struct {
	value *BatchJobsOut
	isSet bool
}

func (v NullableBatchJobsOut) Get() *BatchJobsOut {
	return v.value
}

func (v *NullableBatchJobsOut) Set(val *BatchJobsOut) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchJobsOut) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchJobsOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchJobsOut(val *BatchJobsOut) *NullableBatchJobsOut {
	return &NullableBatchJobsOut{value: val, isSet: true}
}

func (v NullableBatchJobsOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchJobsOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


