/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListDocumentOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDocumentOut{}

// ListDocumentOut struct for ListDocumentOut
type ListDocumentOut struct {
	Pagination PaginationInfo `json:"pagination"`
	Data []DocumentOut `json:"data"`
}

type _ListDocumentOut ListDocumentOut

// NewListDocumentOut instantiates a new ListDocumentOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDocumentOut(pagination PaginationInfo, data []DocumentOut) *ListDocumentOut {
	this := ListDocumentOut{}
	this.Pagination = pagination
	this.Data = data
	return &this
}

// NewListDocumentOutWithDefaults instantiates a new ListDocumentOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDocumentOutWithDefaults() *ListDocumentOut {
	this := ListDocumentOut{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *ListDocumentOut) GetPagination() PaginationInfo {
	if o == nil {
		var ret PaginationInfo
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *ListDocumentOut) GetPaginationOk() (*PaginationInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *ListDocumentOut) SetPagination(v PaginationInfo) {
	o.Pagination = v
}

// GetData returns the Data field value
func (o *ListDocumentOut) GetData() []DocumentOut {
	if o == nil {
		var ret []DocumentOut
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListDocumentOut) GetDataOk() ([]DocumentOut, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListDocumentOut) SetData(v []DocumentOut) {
	o.Data = v
}

func (o ListDocumentOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDocumentOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ListDocumentOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pagination",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListDocumentOut := _ListDocumentOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListDocumentOut)

	if err != nil {
		return err
	}

	*o = ListDocumentOut(varListDocumentOut)

	return err
}

type NullableListDocumentOut struct {
	value *ListDocumentOut
	isSet bool
}

func (v NullableListDocumentOut) Get() *ListDocumentOut {
	return v.value
}

func (v *NullableListDocumentOut) Set(val *ListDocumentOut) {
	v.value = val
	v.isSet = true
}

func (v NullableListDocumentOut) IsSet() bool {
	return v.isSet
}

func (v *NullableListDocumentOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDocumentOut(val *ListDocumentOut) *NullableListDocumentOut {
	return &NullableListDocumentOut{value: val, isSet: true}
}

func (v NullableListDocumentOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDocumentOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


