/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
)


// ConversationInputs struct for ConversationInputs
type ConversationInputs struct {
	ArrayOfConversationHistoryEntriesInner *[]ConversationHistoryEntriesInner
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ConversationInputs) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into ArrayOfConversationHistoryEntriesInner
	err = json.Unmarshal(data, &dst.ArrayOfConversationHistoryEntriesInner);
	if err == nil {
		jsonArrayOfConversationHistoryEntriesInner, _ := json.Marshal(dst.ArrayOfConversationHistoryEntriesInner)
		if string(jsonArrayOfConversationHistoryEntriesInner) == "{}" { // empty struct
			dst.ArrayOfConversationHistoryEntriesInner = nil
		} else {
			return nil // data stored in dst.ArrayOfConversationHistoryEntriesInner, return on the first match
		}
	} else {
		dst.ArrayOfConversationHistoryEntriesInner = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ConversationInputs)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ConversationInputs) MarshalJSON() ([]byte, error) {
	if src.ArrayOfConversationHistoryEntriesInner != nil {
		return json.Marshal(&src.ArrayOfConversationHistoryEntriesInner)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableConversationInputs struct {
	value *ConversationInputs
	isSet bool
}

func (v NullableConversationInputs) Get() *ConversationInputs {
	return v.value
}

func (v *NullableConversationInputs) Set(val *ConversationInputs) {
	v.value = val
	v.isSet = true
}

func (v NullableConversationInputs) IsSet() bool {
	return v.isSet
}

func (v *NullableConversationInputs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConversationInputs(val *ConversationInputs) *NullableConversationInputs {
	return &NullableConversationInputs{value: val, isSet: true}
}

func (v NullableConversationInputs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConversationInputs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


