/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 0.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
)

// checks if the ChatCompletionResponseBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatCompletionResponseBase{}

// ChatCompletionResponseBase struct for ChatCompletionResponseBase
type ChatCompletionResponseBase struct {
	Id *string `json:"id,omitempty"`
	Object *string `json:"object,omitempty"`
	Model *string `json:"model,omitempty"`
	Usage *UsageInfo `json:"usage,omitempty"`
	Created *int32 `json:"created,omitempty"`
}

// NewChatCompletionResponseBase instantiates a new ChatCompletionResponseBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatCompletionResponseBase() *ChatCompletionResponseBase {
	this := ChatCompletionResponseBase{}
	return &this
}

// NewChatCompletionResponseBaseWithDefaults instantiates a new ChatCompletionResponseBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatCompletionResponseBaseWithDefaults() *ChatCompletionResponseBase {
	this := ChatCompletionResponseBase{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ChatCompletionResponseBase) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatCompletionResponseBase) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ChatCompletionResponseBase) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ChatCompletionResponseBase) SetId(v string) {
	o.Id = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *ChatCompletionResponseBase) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatCompletionResponseBase) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *ChatCompletionResponseBase) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *ChatCompletionResponseBase) SetObject(v string) {
	o.Object = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *ChatCompletionResponseBase) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatCompletionResponseBase) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *ChatCompletionResponseBase) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *ChatCompletionResponseBase) SetModel(v string) {
	o.Model = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *ChatCompletionResponseBase) GetUsage() UsageInfo {
	if o == nil || IsNil(o.Usage) {
		var ret UsageInfo
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatCompletionResponseBase) GetUsageOk() (*UsageInfo, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *ChatCompletionResponseBase) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given UsageInfo and assigns it to the Usage field.
func (o *ChatCompletionResponseBase) SetUsage(v UsageInfo) {
	o.Usage = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *ChatCompletionResponseBase) GetCreated() int32 {
	if o == nil || IsNil(o.Created) {
		var ret int32
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChatCompletionResponseBase) GetCreatedOk() (*int32, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *ChatCompletionResponseBase) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given int32 and assigns it to the Created field.
func (o *ChatCompletionResponseBase) SetCreated(v int32) {
	o.Created = &v
}

func (o ChatCompletionResponseBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatCompletionResponseBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	return toSerialize, nil
}

type NullableChatCompletionResponseBase struct {
	value *ChatCompletionResponseBase
	isSet bool
}

func (v NullableChatCompletionResponseBase) Get() *ChatCompletionResponseBase {
	return v.value
}

func (v *NullableChatCompletionResponseBase) Set(val *ChatCompletionResponseBase) {
	v.value = val
	v.isSet = true
}

func (v NullableChatCompletionResponseBase) IsSet() bool {
	return v.isSet
}

func (v *NullableChatCompletionResponseBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatCompletionResponseBase(val *ChatCompletionResponseBase) *NullableChatCompletionResponseBase {
	return &NullableChatCompletionResponseBase{value: val, isSet: true}
}

func (v NullableChatCompletionResponseBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatCompletionResponseBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


