/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArchiveFTModelOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArchiveFTModelOut{}

// ArchiveFTModelOut struct for ArchiveFTModelOut
type ArchiveFTModelOut struct {
	Id string `json:"id"`
	Object *string `json:"object,omitempty"`
	Archived *bool `json:"archived,omitempty"`
}

type _ArchiveFTModelOut ArchiveFTModelOut

// NewArchiveFTModelOut instantiates a new ArchiveFTModelOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArchiveFTModelOut(id string) *ArchiveFTModelOut {
	this := ArchiveFTModelOut{}
	this.Id = id
	var object string = "model"
	this.Object = &object
	var archived bool = true
	this.Archived = &archived
	return &this
}

// NewArchiveFTModelOutWithDefaults instantiates a new ArchiveFTModelOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArchiveFTModelOutWithDefaults() *ArchiveFTModelOut {
	this := ArchiveFTModelOut{}
	var object string = "model"
	this.Object = &object
	var archived bool = true
	this.Archived = &archived
	return &this
}

// GetId returns the Id field value
func (o *ArchiveFTModelOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ArchiveFTModelOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ArchiveFTModelOut) SetId(v string) {
	o.Id = v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *ArchiveFTModelOut) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArchiveFTModelOut) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *ArchiveFTModelOut) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *ArchiveFTModelOut) SetObject(v string) {
	o.Object = &v
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *ArchiveFTModelOut) GetArchived() bool {
	if o == nil || IsNil(o.Archived) {
		var ret bool
		return ret
	}
	return *o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArchiveFTModelOut) GetArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *ArchiveFTModelOut) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given bool and assigns it to the Archived field.
func (o *ArchiveFTModelOut) SetArchived(v bool) {
	o.Archived = &v
}

func (o ArchiveFTModelOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArchiveFTModelOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}
	return toSerialize, nil
}

func (o *ArchiveFTModelOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArchiveFTModelOut := _ArchiveFTModelOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArchiveFTModelOut)

	if err != nil {
		return err
	}

	*o = ArchiveFTModelOut(varArchiveFTModelOut)

	return err
}

type NullableArchiveFTModelOut struct {
	value *ArchiveFTModelOut
	isSet bool
}

func (v NullableArchiveFTModelOut) Get() *ArchiveFTModelOut {
	return v.value
}

func (v *NullableArchiveFTModelOut) Set(val *ArchiveFTModelOut) {
	v.value = val
	v.isSet = true
}

func (v NullableArchiveFTModelOut) IsSet() bool {
	return v.isSet
}

func (v *NullableArchiveFTModelOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArchiveFTModelOut(val *ArchiveFTModelOut) *NullableArchiveFTModelOut {
	return &NullableArchiveFTModelOut{value: val, isSet: true}
}

func (v NullableArchiveFTModelOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArchiveFTModelOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


