/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 0.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
)

// checks if the AgentsCompletionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentsCompletionRequest{}

// AgentsCompletionRequest struct for AgentsCompletionRequest
type AgentsCompletionRequest struct {
	MaxTokens NullableInt32 `json:"max_tokens,omitempty"`
	// Whether to stream back partial progress. If set, tokens will be sent as data-only server-side events as they become available, with the stream terminated by a data: [DONE] message. Otherwise, the server will hold the request open until the timeout or until completion, with the response containing the full result as JSON.
	Stream *bool `json:"stream,omitempty"`
	Stop *Stop1 `json:"stop,omitempty"`
	RandomSeed NullableInt32 `json:"random_seed,omitempty"`
	// The prompt(s) to generate completions for, encoded as a list of dict with role and content.
	Messages []MessagesInner `json:"messages"`
	ResponseFormat *ResponseFormat `json:"response_format,omitempty"`
	Tools []Tool `json:"tools,omitempty"`
	ToolChoice *ToolChoice `json:"tool_choice,omitempty"`
	// presence_penalty determines how much the model penalizes the repetition of words or phrases. A higher presence penalty encourages the model to use a wider variety of words and phrases, making the output more diverse and creative.
	PresencePenalty *float32 `json:"presence_penalty,omitempty"`
	// frequency_penalty penalizes the repetition of words based on their frequency in the generated text. A higher frequency penalty discourages the model from repeating words that have already appeared frequently in the output, promoting diversity and reducing repetition.
	FrequencyPenalty *float32 `json:"frequency_penalty,omitempty"`
	N NullableInt32 `json:"n,omitempty"`
	// Enable users to specify expected results, optimizing response times by leveraging known or predictable content. This approach is especially effective for updating text documents or code files with minimal changes, reducing latency while maintaining high-quality results.
	Prediction *Prediction `json:"prediction,omitempty"`
	ParallelToolCalls *bool `json:"parallel_tool_calls,omitempty"`
	// The ID of the agent to use for this completion.
	AgentId string `json:"agent_id"`
	AdditionalProperties map[string]interface{}
}

type _AgentsCompletionRequest AgentsCompletionRequest

// NewAgentsCompletionRequest instantiates a new AgentsCompletionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentsCompletionRequest(messages []MessagesInner, agentId string) *AgentsCompletionRequest {
	this := AgentsCompletionRequest{}
	var stream bool = false
	this.Stream = &stream
	this.Messages = messages
	var toolChoice ToolChoice = auto
	this.ToolChoice = &toolChoice
	var presencePenalty float32 = 0.0
	this.PresencePenalty = &presencePenalty
	var frequencyPenalty float32 = 0.0
	this.FrequencyPenalty = &frequencyPenalty
	var parallelToolCalls bool = true
	this.ParallelToolCalls = &parallelToolCalls
	this.AgentId = agentId
	return &this
}

// NewAgentsCompletionRequestWithDefaults instantiates a new AgentsCompletionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentsCompletionRequestWithDefaults() *AgentsCompletionRequest {
	this := AgentsCompletionRequest{}
	var stream bool = false
	this.Stream = &stream
	var toolChoice ToolChoice = auto
	this.ToolChoice = &toolChoice
	var presencePenalty float32 = 0.0
	this.PresencePenalty = &presencePenalty
	var frequencyPenalty float32 = 0.0
	this.FrequencyPenalty = &frequencyPenalty
	var parallelToolCalls bool = true
	this.ParallelToolCalls = &parallelToolCalls
	return &this
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentsCompletionRequest) GetMaxTokens() int32 {
	if o == nil || IsNil(o.MaxTokens.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxTokens.Get()
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentsCompletionRequest) GetMaxTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxTokens.Get(), o.MaxTokens.IsSet()
}

// HasMaxTokens returns a boolean if a field has been set.
func (o *AgentsCompletionRequest) HasMaxTokens() bool {
	if o != nil && o.MaxTokens.IsSet() {
		return true
	}

	return false
}

// SetMaxTokens gets a reference to the given NullableInt32 and assigns it to the MaxTokens field.
func (o *AgentsCompletionRequest) SetMaxTokens(v int32) {
	o.MaxTokens.Set(&v)
}
// SetMaxTokensNil sets the value for MaxTokens to be an explicit nil
func (o *AgentsCompletionRequest) SetMaxTokensNil() {
	o.MaxTokens.Set(nil)
}

// UnsetMaxTokens ensures that no value is present for MaxTokens, not even an explicit nil
func (o *AgentsCompletionRequest) UnsetMaxTokens() {
	o.MaxTokens.Unset()
}

// GetStream returns the Stream field value if set, zero value otherwise.
func (o *AgentsCompletionRequest) GetStream() bool {
	if o == nil || IsNil(o.Stream) {
		var ret bool
		return ret
	}
	return *o.Stream
}

// GetStreamOk returns a tuple with the Stream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsCompletionRequest) GetStreamOk() (*bool, bool) {
	if o == nil || IsNil(o.Stream) {
		return nil, false
	}
	return o.Stream, true
}

// HasStream returns a boolean if a field has been set.
func (o *AgentsCompletionRequest) HasStream() bool {
	if o != nil && !IsNil(o.Stream) {
		return true
	}

	return false
}

// SetStream gets a reference to the given bool and assigns it to the Stream field.
func (o *AgentsCompletionRequest) SetStream(v bool) {
	o.Stream = &v
}

// GetStop returns the Stop field value if set, zero value otherwise.
func (o *AgentsCompletionRequest) GetStop() Stop1 {
	if o == nil || IsNil(o.Stop) {
		var ret Stop1
		return ret
	}
	return *o.Stop
}

// GetStopOk returns a tuple with the Stop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsCompletionRequest) GetStopOk() (*Stop1, bool) {
	if o == nil || IsNil(o.Stop) {
		return nil, false
	}
	return o.Stop, true
}

// HasStop returns a boolean if a field has been set.
func (o *AgentsCompletionRequest) HasStop() bool {
	if o != nil && !IsNil(o.Stop) {
		return true
	}

	return false
}

// SetStop gets a reference to the given Stop1 and assigns it to the Stop field.
func (o *AgentsCompletionRequest) SetStop(v Stop1) {
	o.Stop = &v
}

// GetRandomSeed returns the RandomSeed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentsCompletionRequest) GetRandomSeed() int32 {
	if o == nil || IsNil(o.RandomSeed.Get()) {
		var ret int32
		return ret
	}
	return *o.RandomSeed.Get()
}

// GetRandomSeedOk returns a tuple with the RandomSeed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentsCompletionRequest) GetRandomSeedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RandomSeed.Get(), o.RandomSeed.IsSet()
}

// HasRandomSeed returns a boolean if a field has been set.
func (o *AgentsCompletionRequest) HasRandomSeed() bool {
	if o != nil && o.RandomSeed.IsSet() {
		return true
	}

	return false
}

// SetRandomSeed gets a reference to the given NullableInt32 and assigns it to the RandomSeed field.
func (o *AgentsCompletionRequest) SetRandomSeed(v int32) {
	o.RandomSeed.Set(&v)
}
// SetRandomSeedNil sets the value for RandomSeed to be an explicit nil
func (o *AgentsCompletionRequest) SetRandomSeedNil() {
	o.RandomSeed.Set(nil)
}

// UnsetRandomSeed ensures that no value is present for RandomSeed, not even an explicit nil
func (o *AgentsCompletionRequest) UnsetRandomSeed() {
	o.RandomSeed.Unset()
}

// GetMessages returns the Messages field value
func (o *AgentsCompletionRequest) GetMessages() []MessagesInner {
	if o == nil {
		var ret []MessagesInner
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *AgentsCompletionRequest) GetMessagesOk() ([]MessagesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages, true
}

// SetMessages sets field value
func (o *AgentsCompletionRequest) SetMessages(v []MessagesInner) {
	o.Messages = v
}

// GetResponseFormat returns the ResponseFormat field value if set, zero value otherwise.
func (o *AgentsCompletionRequest) GetResponseFormat() ResponseFormat {
	if o == nil || IsNil(o.ResponseFormat) {
		var ret ResponseFormat
		return ret
	}
	return *o.ResponseFormat
}

// GetResponseFormatOk returns a tuple with the ResponseFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsCompletionRequest) GetResponseFormatOk() (*ResponseFormat, bool) {
	if o == nil || IsNil(o.ResponseFormat) {
		return nil, false
	}
	return o.ResponseFormat, true
}

// HasResponseFormat returns a boolean if a field has been set.
func (o *AgentsCompletionRequest) HasResponseFormat() bool {
	if o != nil && !IsNil(o.ResponseFormat) {
		return true
	}

	return false
}

// SetResponseFormat gets a reference to the given ResponseFormat and assigns it to the ResponseFormat field.
func (o *AgentsCompletionRequest) SetResponseFormat(v ResponseFormat) {
	o.ResponseFormat = &v
}

// GetTools returns the Tools field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentsCompletionRequest) GetTools() []Tool {
	if o == nil {
		var ret []Tool
		return ret
	}
	return o.Tools
}

// GetToolsOk returns a tuple with the Tools field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentsCompletionRequest) GetToolsOk() ([]Tool, bool) {
	if o == nil || IsNil(o.Tools) {
		return nil, false
	}
	return o.Tools, true
}

// HasTools returns a boolean if a field has been set.
func (o *AgentsCompletionRequest) HasTools() bool {
	if o != nil && !IsNil(o.Tools) {
		return true
	}

	return false
}

// SetTools gets a reference to the given []Tool and assigns it to the Tools field.
func (o *AgentsCompletionRequest) SetTools(v []Tool) {
	o.Tools = v
}

// GetToolChoice returns the ToolChoice field value if set, zero value otherwise.
func (o *AgentsCompletionRequest) GetToolChoice() ToolChoice {
	if o == nil || IsNil(o.ToolChoice) {
		var ret ToolChoice
		return ret
	}
	return *o.ToolChoice
}

// GetToolChoiceOk returns a tuple with the ToolChoice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsCompletionRequest) GetToolChoiceOk() (*ToolChoice, bool) {
	if o == nil || IsNil(o.ToolChoice) {
		return nil, false
	}
	return o.ToolChoice, true
}

// HasToolChoice returns a boolean if a field has been set.
func (o *AgentsCompletionRequest) HasToolChoice() bool {
	if o != nil && !IsNil(o.ToolChoice) {
		return true
	}

	return false
}

// SetToolChoice gets a reference to the given ToolChoice and assigns it to the ToolChoice field.
func (o *AgentsCompletionRequest) SetToolChoice(v ToolChoice) {
	o.ToolChoice = &v
}

// GetPresencePenalty returns the PresencePenalty field value if set, zero value otherwise.
func (o *AgentsCompletionRequest) GetPresencePenalty() float32 {
	if o == nil || IsNil(o.PresencePenalty) {
		var ret float32
		return ret
	}
	return *o.PresencePenalty
}

// GetPresencePenaltyOk returns a tuple with the PresencePenalty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsCompletionRequest) GetPresencePenaltyOk() (*float32, bool) {
	if o == nil || IsNil(o.PresencePenalty) {
		return nil, false
	}
	return o.PresencePenalty, true
}

// HasPresencePenalty returns a boolean if a field has been set.
func (o *AgentsCompletionRequest) HasPresencePenalty() bool {
	if o != nil && !IsNil(o.PresencePenalty) {
		return true
	}

	return false
}

// SetPresencePenalty gets a reference to the given float32 and assigns it to the PresencePenalty field.
func (o *AgentsCompletionRequest) SetPresencePenalty(v float32) {
	o.PresencePenalty = &v
}

// GetFrequencyPenalty returns the FrequencyPenalty field value if set, zero value otherwise.
func (o *AgentsCompletionRequest) GetFrequencyPenalty() float32 {
	if o == nil || IsNil(o.FrequencyPenalty) {
		var ret float32
		return ret
	}
	return *o.FrequencyPenalty
}

// GetFrequencyPenaltyOk returns a tuple with the FrequencyPenalty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsCompletionRequest) GetFrequencyPenaltyOk() (*float32, bool) {
	if o == nil || IsNil(o.FrequencyPenalty) {
		return nil, false
	}
	return o.FrequencyPenalty, true
}

// HasFrequencyPenalty returns a boolean if a field has been set.
func (o *AgentsCompletionRequest) HasFrequencyPenalty() bool {
	if o != nil && !IsNil(o.FrequencyPenalty) {
		return true
	}

	return false
}

// SetFrequencyPenalty gets a reference to the given float32 and assigns it to the FrequencyPenalty field.
func (o *AgentsCompletionRequest) SetFrequencyPenalty(v float32) {
	o.FrequencyPenalty = &v
}

// GetN returns the N field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentsCompletionRequest) GetN() int32 {
	if o == nil || IsNil(o.N.Get()) {
		var ret int32
		return ret
	}
	return *o.N.Get()
}

// GetNOk returns a tuple with the N field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentsCompletionRequest) GetNOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.N.Get(), o.N.IsSet()
}

// HasN returns a boolean if a field has been set.
func (o *AgentsCompletionRequest) HasN() bool {
	if o != nil && o.N.IsSet() {
		return true
	}

	return false
}

// SetN gets a reference to the given NullableInt32 and assigns it to the N field.
func (o *AgentsCompletionRequest) SetN(v int32) {
	o.N.Set(&v)
}
// SetNNil sets the value for N to be an explicit nil
func (o *AgentsCompletionRequest) SetNNil() {
	o.N.Set(nil)
}

// UnsetN ensures that no value is present for N, not even an explicit nil
func (o *AgentsCompletionRequest) UnsetN() {
	o.N.Unset()
}

// GetPrediction returns the Prediction field value if set, zero value otherwise.
func (o *AgentsCompletionRequest) GetPrediction() Prediction {
	if o == nil || IsNil(o.Prediction) {
		var ret Prediction
		return ret
	}
	return *o.Prediction
}

// GetPredictionOk returns a tuple with the Prediction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsCompletionRequest) GetPredictionOk() (*Prediction, bool) {
	if o == nil || IsNil(o.Prediction) {
		return nil, false
	}
	return o.Prediction, true
}

// HasPrediction returns a boolean if a field has been set.
func (o *AgentsCompletionRequest) HasPrediction() bool {
	if o != nil && !IsNil(o.Prediction) {
		return true
	}

	return false
}

// SetPrediction gets a reference to the given Prediction and assigns it to the Prediction field.
func (o *AgentsCompletionRequest) SetPrediction(v Prediction) {
	o.Prediction = &v
}

// GetParallelToolCalls returns the ParallelToolCalls field value if set, zero value otherwise.
func (o *AgentsCompletionRequest) GetParallelToolCalls() bool {
	if o == nil || IsNil(o.ParallelToolCalls) {
		var ret bool
		return ret
	}
	return *o.ParallelToolCalls
}

// GetParallelToolCallsOk returns a tuple with the ParallelToolCalls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsCompletionRequest) GetParallelToolCallsOk() (*bool, bool) {
	if o == nil || IsNil(o.ParallelToolCalls) {
		return nil, false
	}
	return o.ParallelToolCalls, true
}

// HasParallelToolCalls returns a boolean if a field has been set.
func (o *AgentsCompletionRequest) HasParallelToolCalls() bool {
	if o != nil && !IsNil(o.ParallelToolCalls) {
		return true
	}

	return false
}

// SetParallelToolCalls gets a reference to the given bool and assigns it to the ParallelToolCalls field.
func (o *AgentsCompletionRequest) SetParallelToolCalls(v bool) {
	o.ParallelToolCalls = &v
}

// GetAgentId returns the AgentId field value
func (o *AgentsCompletionRequest) GetAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *AgentsCompletionRequest) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *AgentsCompletionRequest) SetAgentId(v string) {
	o.AgentId = v
}

func (o AgentsCompletionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentsCompletionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.MaxTokens.IsSet() {
		toSerialize["max_tokens"] = o.MaxTokens.Get()
	}
	if !IsNil(o.Stream) {
		toSerialize["stream"] = o.Stream
	}
	if !IsNil(o.Stop) {
		toSerialize["stop"] = o.Stop
	}
	if o.RandomSeed.IsSet() {
		toSerialize["random_seed"] = o.RandomSeed.Get()
	}
	toSerialize["messages"] = o.Messages
	if !IsNil(o.ResponseFormat) {
		toSerialize["response_format"] = o.ResponseFormat
	}
	if o.Tools != nil {
		toSerialize["tools"] = o.Tools
	}
	if !IsNil(o.ToolChoice) {
		toSerialize["tool_choice"] = o.ToolChoice
	}
	if !IsNil(o.PresencePenalty) {
		toSerialize["presence_penalty"] = o.PresencePenalty
	}
	if !IsNil(o.FrequencyPenalty) {
		toSerialize["frequency_penalty"] = o.FrequencyPenalty
	}
	if o.N.IsSet() {
		toSerialize["n"] = o.N.Get()
	}
	if !IsNil(o.Prediction) {
		toSerialize["prediction"] = o.Prediction
	}
	if !IsNil(o.ParallelToolCalls) {
		toSerialize["parallel_tool_calls"] = o.ParallelToolCalls
	}
	toSerialize["agent_id"] = o.AgentId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AgentsCompletionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messages",
		"agent_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentsCompletionRequest := _AgentsCompletionRequest{}

	err = json.Unmarshal(data, &varAgentsCompletionRequest)

	if err != nil {
		return err
	}

	*o = AgentsCompletionRequest(varAgentsCompletionRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "max_tokens")
		delete(additionalProperties, "stream")
		delete(additionalProperties, "stop")
		delete(additionalProperties, "random_seed")
		delete(additionalProperties, "messages")
		delete(additionalProperties, "response_format")
		delete(additionalProperties, "tools")
		delete(additionalProperties, "tool_choice")
		delete(additionalProperties, "presence_penalty")
		delete(additionalProperties, "frequency_penalty")
		delete(additionalProperties, "n")
		delete(additionalProperties, "prediction")
		delete(additionalProperties, "parallel_tool_calls")
		delete(additionalProperties, "agent_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAgentsCompletionRequest struct {
	value *AgentsCompletionRequest
	isSet bool
}

func (v NullableAgentsCompletionRequest) Get() *AgentsCompletionRequest {
	return v.value
}

func (v *NullableAgentsCompletionRequest) Set(val *AgentsCompletionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentsCompletionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentsCompletionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentsCompletionRequest(val *AgentsCompletionRequest) *NullableAgentsCompletionRequest {
	return &NullableAgentsCompletionRequest{value: val, isSet: true}
}

func (v NullableAgentsCompletionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentsCompletionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


