/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 0.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
)

// checks if the ReferenceChunk type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReferenceChunk{}

// ReferenceChunk struct for ReferenceChunk
type ReferenceChunk struct {
	ReferenceIds []int32 `json:"reference_ids"`
	Type *string `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReferenceChunk ReferenceChunk

// NewReferenceChunk instantiates a new ReferenceChunk object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReferenceChunk(referenceIds []int32) *ReferenceChunk {
	this := ReferenceChunk{}
	this.ReferenceIds = referenceIds
	var type_ string = "reference"
	this.Type = &type_
	return &this
}

// NewReferenceChunkWithDefaults instantiates a new ReferenceChunk object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferenceChunkWithDefaults() *ReferenceChunk {
	this := ReferenceChunk{}
	var type_ string = "reference"
	this.Type = &type_
	return &this
}

// GetReferenceIds returns the ReferenceIds field value
func (o *ReferenceChunk) GetReferenceIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.ReferenceIds
}

// GetReferenceIdsOk returns a tuple with the ReferenceIds field value
// and a boolean to check if the value has been set.
func (o *ReferenceChunk) GetReferenceIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferenceIds, true
}

// SetReferenceIds sets field value
func (o *ReferenceChunk) SetReferenceIds(v []int32) {
	o.ReferenceIds = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ReferenceChunk) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferenceChunk) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ReferenceChunk) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ReferenceChunk) SetType(v string) {
	o.Type = &v
}

func (o ReferenceChunk) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReferenceChunk) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reference_ids"] = o.ReferenceIds
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReferenceChunk) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reference_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReferenceChunk := _ReferenceChunk{}

	err = json.Unmarshal(data, &varReferenceChunk)

	if err != nil {
		return err
	}

	*o = ReferenceChunk(varReferenceChunk)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "reference_ids")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReferenceChunk struct {
	value *ReferenceChunk
	isSet bool
}

func (v NullableReferenceChunk) Get() *ReferenceChunk {
	return v.value
}

func (v *NullableReferenceChunk) Set(val *ReferenceChunk) {
	v.value = val
	v.isSet = true
}

func (v NullableReferenceChunk) IsSet() bool {
	return v.isSet
}

func (v *NullableReferenceChunk) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferenceChunk(val *ReferenceChunk) *NullableReferenceChunk {
	return &NullableReferenceChunk{value: val, isSet: true}
}

func (v NullableReferenceChunk) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferenceChunk) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


