/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
)

// checks if the WebSearchTool type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSearchTool{}

// WebSearchTool struct for WebSearchTool
type WebSearchTool struct {
	Type *string `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WebSearchTool WebSearchTool

// NewWebSearchTool instantiates a new WebSearchTool object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSearchTool() *WebSearchTool {
	this := WebSearchTool{}
	var type_ string = "web_search"
	this.Type = &type_
	return &this
}

// NewWebSearchToolWithDefaults instantiates a new WebSearchTool object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSearchToolWithDefaults() *WebSearchTool {
	this := WebSearchTool{}
	var type_ string = "web_search"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *WebSearchTool) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebSearchTool) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *WebSearchTool) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *WebSearchTool) SetType(v string) {
	o.Type = &v
}

func (o WebSearchTool) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSearchTool) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebSearchTool) UnmarshalJSON(data []byte) (err error) {
	varWebSearchTool := _WebSearchTool{}

	err = json.Unmarshal(data, &varWebSearchTool)

	if err != nil {
		return err
	}

	*o = WebSearchTool(varWebSearchTool)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebSearchTool struct {
	value *WebSearchTool
	isSet bool
}

func (v NullableWebSearchTool) Get() *WebSearchTool {
	return v.value
}

func (v *NullableWebSearchTool) Set(val *WebSearchTool) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSearchTool) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSearchTool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSearchTool(val *WebSearchTool) *NullableWebSearchTool {
	return &NullableWebSearchTool{value: val, isSet: true}
}

func (v NullableWebSearchTool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSearchTool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


