/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
)

// checks if the FunctionCall type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FunctionCall{}

// FunctionCall struct for FunctionCall
type FunctionCall struct {
	Name string `json:"name"`
	Arguments Arguments `json:"arguments"`
	AdditionalProperties map[string]interface{}
}

type _FunctionCall FunctionCall

// NewFunctionCall instantiates a new FunctionCall object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionCall(name string, arguments Arguments) *FunctionCall {
	this := FunctionCall{}
	this.Name = name
	this.Arguments = arguments
	return &this
}

// NewFunctionCallWithDefaults instantiates a new FunctionCall object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionCallWithDefaults() *FunctionCall {
	this := FunctionCall{}
	return &this
}

// GetName returns the Name field value
func (o *FunctionCall) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FunctionCall) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FunctionCall) SetName(v string) {
	o.Name = v
}

// GetArguments returns the Arguments field value
func (o *FunctionCall) GetArguments() Arguments {
	if o == nil {
		var ret Arguments
		return ret
	}

	return o.Arguments
}

// GetArgumentsOk returns a tuple with the Arguments field value
// and a boolean to check if the value has been set.
func (o *FunctionCall) GetArgumentsOk() (*Arguments, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Arguments, true
}

// SetArguments sets field value
func (o *FunctionCall) SetArguments(v Arguments) {
	o.Arguments = v
}

func (o FunctionCall) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FunctionCall) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["arguments"] = o.Arguments

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FunctionCall) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"arguments",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFunctionCall := _FunctionCall{}

	err = json.Unmarshal(data, &varFunctionCall)

	if err != nil {
		return err
	}

	*o = FunctionCall(varFunctionCall)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "arguments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFunctionCall struct {
	value *FunctionCall
	isSet bool
}

func (v NullableFunctionCall) Get() *FunctionCall {
	return v.value
}

func (v *NullableFunctionCall) Set(val *FunctionCall) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionCall) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionCall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionCall(val *FunctionCall) *NullableFunctionCall {
	return &NullableFunctionCall{value: val, isSet: true}
}

func (v NullableFunctionCall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionCall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


