/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 0.0.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
)


// RandomSeed The seed to use for random sampling. If set, different calls will generate deterministic results.
type RandomSeed struct {
	Int32 *int32
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *RandomSeed) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	// try to unmarshal JSON data into Int32
	err = json.Unmarshal(data, &dst.Int32);
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			return nil // data stored in dst.Int32, return on the first match
		}
	} else {
		dst.Int32 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(RandomSeed)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RandomSeed) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableRandomSeed struct {
	value *RandomSeed
	isSet bool
}

func (v NullableRandomSeed) Get() *RandomSeed {
	return v.value
}

func (v *NullableRandomSeed) Set(val *RandomSeed) {
	v.value = val
	v.isSet = true
}

func (v NullableRandomSeed) IsSet() bool {
	return v.isSet
}

func (v *NullableRandomSeed) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRandomSeed(val *RandomSeed) *NullableRandomSeed {
	return &NullableRandomSeed{value: val, isSet: true}
}

func (v NullableRandomSeed) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRandomSeed) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


