/*
Mistral AI API

Our Chat Completion and Embeddings APIs specification. Create your account on [La Plateforme](https://console.mistral.ai) to get access and read the [docs](https://docs.mistral.ai) to learn how to use it.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mistral

import (
	"encoding/json"
	"fmt"
)


// ConnectorTokens struct for ConnectorTokens
type ConnectorTokens struct {
	Int32 *int32
	Any *interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ConnectorTokens) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Int32
	err = json.Unmarshal(data, &dst.Int32);
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			return nil // data stored in dst.Int32, return on the first match
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal JSON data into Any
	err = json.Unmarshal(data, &dst.Any);
	if err == nil {
		jsonAny, _ := json.Marshal(dst.Any)
		if string(jsonAny) == "{}" { // empty struct
			dst.Any = nil
		} else {
			return nil // data stored in dst.Any, return on the first match
		}
	} else {
		dst.Any = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ConnectorTokens)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ConnectorTokens) MarshalJSON() ([]byte, error) {
	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.Any != nil {
		return json.Marshal(&src.Any)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableConnectorTokens struct {
	value *ConnectorTokens
	isSet bool
}

func (v NullableConnectorTokens) Get() *ConnectorTokens {
	return v.value
}

func (v *NullableConnectorTokens) Set(val *ConnectorTokens) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorTokens) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorTokens) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorTokens(val *ConnectorTokens) *NullableConnectorTokens {
	return &NullableConnectorTokens{value: val, isSet: true}
}

func (v NullableConnectorTokens) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorTokens) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


